# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.16.0
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.4.1+mc26.1
maven_group=too.cheap
archives_base_name=too-cheap

# Dependencies
cloth_version=26.1.154
modmenu_version=18.0.0-alpha.8